---
# yamllint disable rule:truthy
# .goreleaser.ci.yaml
# Minimal GoReleaser config for CI dry-run validation.
# Only builds linux/amd64 to validate the release config works.
# The full release uses .goreleaser.yaml which builds all platforms.
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: llm-testing
    main: .
    binary: llm-testing
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - id: default
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  disable: true
